# Projeto #2 - Classificador supervisionado

Antes de começar, leia as [Instruções](https://github.com/thvmm/pos-ds-ia/tree/master/projeto_2#instru%C3%A7%C3%B5es) e os [Critérios de Avaliação](https://github.com/thvmm/pos-ds-ia/tree/master/projeto_2#crit%C3%A9rios-de-avalia%C3%A7%C3%A3o)


### 1) Qual a base escolhida?

Reuters Corpus Volume I, pois meu interesse maior nesse momento é análise de texto (revisão de literatura).

### 2) **(10%)** Pré-processamento: entendimento do conjunto de dados


In [1]:
# Carregando a base: rodou a primeira vez, e salvei cada conjunto em um arquivo específico para futuros acessos
#from sklearn.datasets import fetch_rcv1
#rcv1 = fetch_rcv1()

# Salvando os dados
from scipy import sparse
#sparse.save_npz("data.npz", rcv1.data)
#sparse.save_npz("target.npz", rcv1.target)
import numpy as np
#np.savetxt("sample_id.npy", rcv1.sample_id)
#np.savetxt("target_names.npy", rcv1.target_names, fmt="%s")

In [2]:
# Carregando a base a partir dos arquivos salvos na primeira rodada
data = sparse.load_npz("data.npz")
target = sparse.load_npz("target.npz")
sample_id = np.loadtxt("sample_id.npy")
target_names = np.loadtxt("target_names.npy", dtype="O")


In [15]:
# Quais são minhas features?
# Difícil listar, são 47.236...
data.shape

(804414, 47236)

In [21]:
# Quais são minhas classes?
# São 103 classes, que representam os tópicos aos quais os textos podem estar relacionados
print(target_names.shape)
target_names

(103,)


array(['C11', 'C12', 'C13', 'C14', 'C15', 'C151', 'C1511', 'C152', 'C16',
       'C17', 'C171', 'C172', 'C173', 'C174', 'C18', 'C181', 'C182',
       'C183', 'C21', 'C22', 'C23', 'C24', 'C31', 'C311', 'C312', 'C313',
       'C32', 'C33', 'C331', 'C34', 'C41', 'C411', 'C42', 'CCAT', 'E11',
       'E12', 'E121', 'E13', 'E131', 'E132', 'E14', 'E141', 'E142',
       'E143', 'E21', 'E211', 'E212', 'E31', 'E311', 'E312', 'E313',
       'E41', 'E411', 'E51', 'E511', 'E512', 'E513', 'E61', 'E71', 'ECAT',
       'G15', 'G151', 'G152', 'G153', 'G154', 'G155', 'G156', 'G157',
       'G158', 'G159', 'GCAT', 'GCRIM', 'GDEF', 'GDIP', 'GDIS', 'GENT',
       'GENV', 'GFAS', 'GHEA', 'GJOB', 'GMIL', 'GOBIT', 'GODD', 'GPOL',
       'GPRO', 'GREL', 'GSCI', 'GSPO', 'GTOUR', 'GVIO', 'GVOTE', 'GWEA',
       'GWELF', 'M11', 'M12', 'M13', 'M131', 'M132', 'M14', 'M141',
       'M142', 'M143', 'MCAT'], dtype=object)

In [34]:
# Como estão distribuidas minhas classes?
# Cada texto está vinculado a pelo menos um tópico, e até a 17 tópicos. Existem 5 ocorrências da classe 'GMIL', variando até 381.327 para a classe 'CCAT'
print(data.indptr[:6])
print(data.indices[:6])
print(sample_id[:6])

print(target.indptr[:6])
print(target.indices[:6])

[  0 138 319 460 601 679]
[ 863 1522 1680 2292 2844 2866]
[2286. 2287. 2288. 2289. 2290. 2291.]
[ 0  5  7 14 17 20]
[ 34  59  93  94 102  21]


In [6]:
# Checagem se os valores estão dentro de um limite permitido ou razoável.


In [7]:
# Tratamento de valores ausentes por eliminação ou substituição.


In [8]:
# Conversão do tipo de dados.


### 3) **(80%)** Nos blocos seguintes implemente seus classificadores (serão implementados 2 métodos diferentes).

#### 3.1) Qual método escolhido?

*Indique o método escolhido*

#### 3.2) **(10%)** Baseline - Implemente seu classificador da forma mais simples possível para esse ser seu baseline

In [9]:
# Implementação. Use mais blocos se achar que ficará mais organizado.

#### 3.3) **(20%)** Versão 1 - O que podemos fazer para melhorar nosso baseline? Aplique técnicas como redução de dimensionalidade, normalização ou outras. Compare os resultados.

In [10]:
# Implementação. Use mais blocos se achar que ficará mais organizado.

#### 3.4) **(10%)** Tunning - Agora que temos um resultado promissor, vamos tentar melhorar o resultado alterando um ou mais hiper-parametro. Compare os resultados.

In [11]:
# Implementação. Use mais blocos se achar que ficará mais organizado.

#### 3.5) Qual método escolhido?

Indique o método escolhido

#### 3.6) **(10%)** Baseline - Implemente seu classificador da forma mais simples possível para esse ser seu baseline

In [13]:
# Implementação. Use mais blocos se achar que ficará mais organizado.

#### 3.7) **(20%)** Versão 1 - O que podemos fazer para melhorar nosso baseline? Aplique técnicas como redução de dimensionalidade, normalização ou outras. Compare os resultados.

In [12]:
# Implementação. Use mais blocos se achar que ficará mais organizado.

#### 3.8) **(10%)** Tunning - Agora que temos um resultado promissor, vamos tentar melhorar o resultado alterando um ou mais hiper-parametro. Compare os resultados.

In [14]:
# Implementação. Use mais blocos se achar que ficará mais organizado.

### 5) **(10%)** Conclusões

*Compare seus resultados. Imaginando que sua solução fosse para produção, qual deles você escolheria? Por que? Quais os riscos você enxerga? O que recomendaria de próximos passos para melhorar os resultados?*